language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t amarieob/docker-react -f Dockerfile.dev .

script:
  -docker run amarieob/docker-react npm run test -- --coverage